apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: __DEPLOYMENT__-strip
  namespace: __NAMESPACE__
spec:
  stripPrefix:
    prefixes:
      - /__DEPLOYMENT__
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: __DEPLOYMENT__
  namespace: __NAMESPACE__
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/__DEPLOYMENT__`)
      kind: Rule
      middlewares:
        - name: __DEPLOYMENT__-strip
      services:
        - name: __DEPLOYMENT__
          port: 80