version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"     # AMQP protocol (apps connect here)
      - "15672:15672"   # Management UI

    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev
      RABBITMQ_DEFAULT_VHOST: /

      # optional but useful
      RABBITMQ_ERLANG_COOKIE: "supersecretcookie"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 15s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
  rabbitmq_logs: